<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5TaKIdW\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5TaKIdW/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5TaKIdW.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5TaKIdW\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5TaKIdW\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5TaKIdW',
    'container.build_id' => '1b8f894e',
    'container.build_time' => 1532797840,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5TaKIdW');
