<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerIZjV3SY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIZjV3SY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIZjV3SY.legacy');
=======
if (\class_exists(\ContainerXOGT0OR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXOGT0OR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXOGT0OR.legacy');
>>>>>>> master

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerIZjV3SY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIZjV3SY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IZjV3SY',
    'container.build_id' => '17a2f406',
    'container.build_time' => 1532727115,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIZjV3SY');
=======
    \class_alias(\ContainerXOGT0OR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXOGT0OR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XOGT0OR',
    'container.build_id' => '5491bce1',
    'container.build_time' => 1532774254,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXOGT0OR');
>>>>>>> master
